version: '3.8'  # Use the latest version compatible with your Docker installation

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: username  # Set your username
      POSTGRES_PASSWORD: password  # Set your password
      POSTGRES_DB: test  # Set your database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Set your RabbitMQ username
      RABBITMQ_DEFAULT_PASS: guest  # Set your RabbitMQ password

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis default port

volumes:
  postgres_data:  # Named volume for Postgres data persistence